controller_manager:
  ros__parameters:
    update_rate: 100

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["left wheel motor"]
    right_wheel_names: ["right wheel motor"]

    wheel_separation: 0.16
    wheel_radius: 0.033

    wheel_separation_multiplier: 1.112

    use_stamped_vel: false
    base_frame_id: "base_link"
    
    linear:
      x:
        max_velocity: 100.0  # SUPER MAXIMUM - 100 m/s
        min_velocity: -100.0
    angular:
      z:
        max_velocity: 100.0  # SUPER MAXIMUM - 100 rad/s

joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - LDS-01_secondary_motor
      - LDS-01_main_motor

